 
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.
# Test file for use on Ubuntu 20.04.01 LTS with ZFS file system

# Example options
ansible_nas_hostname: ansible-nas
ansible_nas_timezone: America/Phoenix

## Enable some applications
#heimdall port 10080
heimdall_enabled: true
#portainer port 9000
portainer_enabled: true
#netdata port 19999
netdata_enabled: true
#krusader port 5800, password topsecret
krusader_enabled: true
watchtower_enabled: true
#timemachine 10445
timemachine_enabled: true
#pihole 11080
pihole_enabled: true

# Downloading
#transmission port 9092
transmission_enabled: true

# Media Serving
#plex port 32400
plex_enabled: true

# Media sourcing
#sonarr port 8989
sonarr_enabled: true
#radarr port 7878
radarr_enabled: true

# Home automation
#homebridge port 8087
homebridge_enabled: true

samba_shares_root: /tank

docker_storage_driver: zfs
